version: 2.1

definitions:
  jobs:
    - docker: &docker
        - image: cimg/node:18.7.0
    - step: &ci
        - checkout:
            path: ~/github-actions
        - run:
            name: Install Dependencies
            command: yarn install --frozen-lockfile
        - run:
            name: Run Linting
            command: yarn lint
        - run:
            name: Run Tests
            command: yarn test

jobs:
  angular:
    working_directory: ~/github-actions/frontend
    docker: *docker
    steps: *ci
  nestjs:
    working_directory: ~/github-actions/backend
    docker: *docker
    steps: *ci

workflows:
  angular-ci-workflow:
    jobs:
      - angular
  nestjs-ci-workflow:
    jobs:
      - nestjs
